---
- hosts: localhost
  connection: local
  sudo: yes
  remote_user: jenkins
  vars:
    copr_repo_url: https://copr.fedorainfracloud.org/coprs/blpdevtools/docker-config/repo/epel-7/blpdevtools-docker-config-epel-7.repo
    copr_repo_gpg_key_url: https://copr-be.cloud.fedoraproject.org/results/blpdevtools/docker-config/pubkey.gpg
    network: 192.168.0.0
  tasks:
    - name: Install Copr BLPDevTools repo.
      get_url: "url={{ copr_repo_url }}
               dest='/etc/yum.repos.d/blpdevtools.repo'
               mode=0440"

    - name: Import Copr GPG key.
      rpm_key:
        key: "{{ copr_repo_gpg_key_url }}"
        state: present

    - name: Install docker
      yum: name=docker state=latest

    - name: Install docker-config
      yum: name=docker-config state=latest

    - name: check current DOCKER_NETWORK_OPTIONS
      shell: "grep 'DOCKER_NETWORK_OPTIONS' /etc/sysconfig/docker-network "
      register: options
      failed_when: " '{{ network }}' not in options.stdout"


